### ISSUE TITLE
Adicionar documento sobre metodologias.

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2019.2-Chatbot-Nilo#102]
## Descrição

O repositória ainda não tem uma documentação a respeito de como estão sendo utilizadas as metodologias ageis. Devem ser adicionados estes documentos.

## Tasks(Tarefas)

- [ ] Adicionar documento a respeito do scrum e XP.
- [ ] Detalhamento de Sprints e métricas.

## Critérios de Aceitação
- [ ] Cumprir as tarefas listadas anteriormente.
