### ISSUE TITLE
Corrigir o Documento de Arquitetura.

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2019.2-Chatbot-Nilo#27]
## Descrição

Incluir maior detalhamento da arquitetura do produto.

## Tasks(Tarefas)

- [x] Criar um diagrama de pacotes do bot
- [x] Detalhar o Backend e Frontend.
- [x] Incluir a arquitetura do Rasa.

## Critérios de Aceitação

- [x] Cumprir todas as tarefas previstas.
