### ISSUE TITLE
Melhorar as actions relacionadas ao estágio.

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2019.2-Chatbot-Nilo#29]
## Descrição

As `actions` relacionadas ao estágio, estão sem sentido, e a maioria delas são desnecessárias. Com base nisso as actions que são desnecessárias se tornarão `utters`, pois se tratam de tarefas constantes que podem ser tratadas como texto.

## Tasks(Tarefas)

- [ ] Adaptar as actions desnecessárias em `utters`.
- [ ] Melhorar as actions que permanecerão. 

## Critérios de Aceitação

- [ ]  Cumprir as tarefas previstas anteriormente de forma eficiente.

**Comment by httpaiva** [comment]
Boa tarde. Após adaptar as actions citadas para utters, ainda é necessário manter o arquivo "procura_respostas.py" no projeto?

**Comment by eliseukadesh67** [comment]
> Boa tarde. Após adaptar as actions citadas para utters, ainda é necessário manter o arquivo "procura_respostas.py" no projeto?

Boa tarde. O arquivo pode ser removido, ja que ele não possui mais funcionalidade.
