### ISSUE TITLE
Atualizar o /start

### ISSUE THREAD

**Issue by httpaiva** [fga-eps-mds/2019.2-Chatbot-Nilo#89]
## Descrição

A intent /start do projeto ainda está referenciando os conhecimentos do bot na Release 1. Essa intent precisa ser atualizada com os novos assuntos que o bot pode tratar e também seria interessante que ele cite a existência do /help.

## Tasks(Tarefas).

- [ ] Referencias todos os assuntos que o bot trata.
- [x] Referenciar o /help para auxiliar o usuário.

## Critérios de Aceitação
- [ ] Cumprir todas as tarefas acima.
